rails/blueprint/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  #
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  #default route
  #get ':controller(/:action(/:id))'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

rails/blueprint/app/models/page.rb
class Page < ApplicationRecord
    belongs_to :subject
end

rails/blueprint/app/models/subject.rb
class Subject < ApplicationRecord
    has_many :pages
end

rails/blueprint/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

rails/blueprint/app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  def index
    @pages = Page.order('position ASC')
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    # @subject = Subject.find(page_params[:subject_id])
    # @page.subject = @subject 
    if @page.save
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(page_params) 
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy 
    redirect_to(pages_path)
  end

  private

    def page_params
      params.require(:page).permit(:name, :permalink, :visible, :position, :content, :subject_id)
    end
end

rails/blueprint/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  def index
    @subjects = Subject.order('position ASC')
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to(subjects_path)
    else
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params) 
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy 
    redirect_to(subjects_path)
  end

  private

    def subject_params
      params.require(:subject).permit(:name, :visible, :position)
    end
end

rails/blueprint/app/helpers/application_helper.rb
module ApplicationHelper

    def error_messages_for(object)
        render(:partial => 'application/error_messages', :locals => {:object => object} )
    end

end

rails/blueprint/app/helpers/home_helper.rb
module HomeHelper
end

rails/blueprint/app/helpers/pages_helper.rb
module PagesHelper
end

rails/blueprint/app/helpers/subjects_helper.rb
module SubjectsHelper
end

rails/blueprint/app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

rails/blueprint/app/views/home/index.html.erb
<h1>Blueprint Blog Home</h1>
<p><%= link_to('All subjects', subjects_path) %></p>

rails/blueprint/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blueprint</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/blueprint/app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Page form fields">
    <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
    <th>PermaLink</th>
    <td><%= f.text_field(:permalink) %></td>
    </tr>
    <tr>
    <th>Position</th>
    <td><%= f.text_field(:position) %></td>
    </tr>
    <tr>
    <th>Visible</th>
    <td><%= f.text_field(:visible) %></td>
    </tr>
    <tr>
    <th>Content</th>
    <td><%= f.text_area(:content, :rows => 10, :cols => 60) %></td>
    </tr>
    <tr>
    <th>Subject</th>
    <td><%= f.text_field(:subject_id) %></td>
    </tr>
</table>

rails/blueprint/app/views/pages/delete.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>

  <%= form_for(@page, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this page?</p>
    <p><%= @page.name%></p>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>
</div>

rails/blueprint/app/views/pages/edit.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages new">
  <h2>Update Page</h2>

  <%= form_for(@page) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>

    <%= link_to("Cancel", page_path(@page), :class => 'back-link') %>
  <% end %>
</div>

rails/blueprint/app/views/pages/index.html.erb
<div class="pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page", new_page_path , :class => 'action new') %>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Page</th>
      <th>Position</th>
      <th>Visible</th>
      <th>Subject</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.id %></td>
      <td><%= page.name %></td>
      <td><%= page.position %></td>
      <td class="center"><%= page.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= page.subject.name %></td>
      <td class="actions">
        <%= link_to("Show", page_path(page), :class => "action show") %>
        <%= link_to("Edit", edit_page_path(page), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

rails/blueprint/app/views/pages/new.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages new">
  <h2>Create Page</h2>

  <%= form_for(@page, :url => pages_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>
</div>

rails/blueprint/app/views/pages/show.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>

  <%= link_to("Edit", edit_page_path(@page), :class => 'action edit') %> | <%= link_to("Delete", delete_page_path(@page), :class => 'action delete') %>
  <table summary="Page detail view">
    <tr>
      <th>Id</th>
      <td><%= @page.id %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= @page.content %></td>
    </tr>
    <tr>
      <th>Subject</th>
      <td><%= @page.subject.name  %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>

rails/blueprint/app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
    <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
    </tr>
    <tr>
    <th>Position</th>
    <td><%= f.text_field(:position) %></td>
    </tr>
    <tr>
    <th>Visible</th>
    <td><%= f.text_field(:visible) %></td>
    </tr>
</table>

rails/blueprint/app/views/subjects/delete.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>

  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>
    <p><%= @subject.name%></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

rails/blueprint/app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

    <%= link_to("Cancel", subject_path(@subject), :class => 'back-link') %>
  <% end %>
</div>

rails/blueprint/app/views/subjects/index.html.erb
<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path , :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Position</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.id %></td>
      <td><%= subject.name %></td>
      <td><%= subject.position %></td>
      <td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => "action show") %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

rails/blueprint/app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

rails/blueprint/app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <%= link_to("Edit", edit_subject_path(@subject), :class => 'action edit') %> | <%= link_to("Delete", delete_subject_path(@subject), :class => 'action delete') %>
  <table summary="Subject detail view">
    <tr>
      <th>Id</th>
      <td><%= @subject.id %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>